/* eslint-disable max-len */
export const FETCH_DATA_SUCCESS_ARTIST = 'FETCH_DATA_SUCCESS_ARTIST';
export const FETCH_DATA_SUCCESS_TRACK = 'FETCH_DATA_SUCCESS_TRACK';

export const FETCH_DATA_SUCCESS_SEARCH_ARTIST = 'FETCH_DATA_SUCCESS_SEARCH_ARTIST';
export const FETCH_DATA_SUCCESS_SEARCH_TRACK = 'FETCH_DATA_SUCCESS_SEARCH_TRACK';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_IS_LOADING = 'FETCH_IS_LOADING';
export const FETCH_SHOWS_SUCCESS = 'FETCH_SHOWS_SUCCESS';
export const FETCH_HAS_ERRORED = 'FETCH_HAS_ERRORED';


export const FETCH_ARTIST_DETAIL = 'FETCH_ARTIST_DETAIL';
export const FETCH_TRACK_DETAIL = 'FETCH_TRACK_DETAIL';

export const INPUT_CHANGE = 'INPUT_CHANGE';
export const IS_LOADING = 'IS_LOADING';
